# Generated by Django 5.0 on 2023-12-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='', max_length=70)),
                ('category', models.CharField(default='', max_length=50)),
                ('source_url', models.URLField(default='')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('feed_information', models.JSONField(default='')),
            ],
        ),
    ]
