# Generated by Django 5.0 on 2023-12-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_information',
            field=models.JSONField(default=dict),
        ),
    ]
