# Generated by Django 5.0 on 2024-02-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(default='', max_length=150)),
                ('item_category', models.CharField(blank=True, default='', max_length=100)),
                ('item_url', models.URLField(default='')),
                ('image_source', models.URLField(blank=True, default='')),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='', max_length=150)),
                ('source_image', models.URLField(blank=True, default='')),
                ('source_description', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(default='')),
            ],
            options={
                'ordering': ['source_name'],
            },
        ),
    ]
