# Generated by Django 5.0 on 2024-02-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='source_url',
            field=models.URLField(default='', unique=True),
        ),
    ]
