# Generated by Django 5.0 on 2024-02-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_alter_feed_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='source_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
